### ISSUE TITLE
Test area error

### ISSUE THREAD

**Issue by FSkavlem** [selabhvl/ing301-projectpartA-startcode#1]
When all rooms combined iaw. https://github.com/selabhvl/ing301public/blob/main/project/demo.md this accumulates to 146.55.
In schematic the hallway on second floor is missing sizing, i can only assume that this is to be 10m^2.

https://github.com/selabhvl/ing301-projectpartA-startcode/blob/44f09caf9e0823f754b250ad5a27375bc5659da2/smarthouse_test.py#L11-L12

**Comment by webminz** [comment]
Hei Fredrik!
Du har helt rett! Testkoden ble ikke fullstendig synkronisert med alle endringene vi gjorde før den ble legget ut. 
Du kan bare oppdatere linje 9 i smarthouse_test.py og erstatte 11 med 12 (altså legge til gangen).
Vi har oppdatert både ing301public og denne starterkode repo'en med manglende/feil informasjon.
